### ISSUE TITLE
Error when i lunch payload!

### ISSUE THREAD

**Issue by Cryptonite1337** [De3vil/steal_ps#1]
Traceback (most recent call last):
  File "file_chrom.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "chrom_passowrd.py", line 7, in <module>
ModuleNotFoundError: No module named 'Crypto'
 

this is the error when i am launching the payload or someone (target)

**Comment by De3vil** [comment]
What is the operating system you are working on ?
If you are using Windows, it works fine without any problems.
But if you are using Linux, this tool does not work on Linux, there is a problem with some packages that cannot be installed on Linux, but in the next version I will work to solve this problem,
You can try this temporary solution now
###
rm /var/lib/dpkg/lock
rm /var/cache/apt/archives/lock
rm /var/lib/apt/lists/lock
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install -y wine python-pip 
wget https://www.python.org/ftp/python/2.7.14/python-2.7.14.msi
wine msiexec /i python-2.7.14.msi
sudo wine ~/.wine/drive_c/Python27/python.exe -m pip install pyinstaller==3.6 pynput==1.6.8 pycryptodome==3.14.1 pywin32 mega.py==1.0.8
sudo pip install pynput==1.6.8 pyinstaller==3.3.1
apt install -y gnome-shell-extension-dashtodock
###
Then you can write a simple Python file containing this command and try the command, I don't promise you that it will work because the problem is from Python
`
import subproces  ,os
`
`
WINDOWS_PYTHON_INTERPRETER_PATH = os.path.expanduser("~/.wine/drive_c/Python27/Scripts/pyinstaller.exe")
`
`
subprocess.call(["wine", WINDOWS_PYTHON_INTERPRETER_PATH, "--onefile", "--noconsole", 'file_chrom.py'])
`
